import {
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Bell,
  Building2,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Cloud,
  Compass,
  CreditCard,
  ExternalLink,
  FileText,
  Hand,
  Home,
  Image as ImageIcon,
  LogOut,
  Mail,
  Map,
  MoreHorizontal,
  MoreVertical,
  Paintbrush,
  Pencil,
  Phone,
  PlusCircle,
  Redo2,
  RefreshCw,
  Search,
  Shield,
  SkipForward,
  SlidersHorizontal,
  Star,
  Trash2,
  Type,
  Undo2,
  User,
  X,
  XCircle,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react-native';

/** Maps the Ionicons names previously used across the app to their Lucide equivalents. */
const ICONS = {
  'add-circle-outline': PlusCircle,
  'arrow-down-outline': ArrowDown,
  'arrow-forward': ArrowRight,
  'arrow-redo-outline': Redo2,
  'arrow-undo-outline': Undo2,
  'arrow-forward-outline': ArrowRight,
  'arrow-up-outline': ArrowUp,
  'brush-outline': Paintbrush,
  'business-outline': Building2,
  'call-outline': Phone,
  camera: Camera,
  'camera-outline': Camera,
  'card-outline': CreditCard,
  checkmark: Check,
  'checkmark-circle': CheckCircle2,
  'checkmark-circle-outline': CheckCircle2,
  'chevron-back': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-forward': ChevronRight,
  'chevron-up': ChevronUp,
  clipboard: Clipboard,
  'clipboard-outline': Clipboard,
  close: X,
  'close-circle': XCircle,
  'cloud-outline': Cloud,
  'compass-outline': Compass,
  'document-text-outline': FileText,
  'ellipse-outline': Circle,
  'ellipsis-horizontal': MoreHorizontal,
  'ellipsis-vertical': MoreVertical,
  'hand-left-outline': Hand,
  home: Home,
  'home-outline': Home,
  'id-card-outline': CreditCard,
  'image-outline': ImageIcon,
  'log-out-outline': LogOut,
  'mail-outline': Mail,
  'map-outline': Map,
  notifications: Bell,
  'notifications-outline': Bell,
  'open-outline': ExternalLink,
  'options-outline': SlidersHorizontal,
  pencil: Pencil,
  person: User,
  'person-outline': User,
  'play-skip-forward': SkipForward,
  'refresh-outline': RefreshCw,
  search: Search,
  'shield-outline': Shield,
  'star-outline': Star,
  'swap-horizontal-outline': ArrowLeftRight,
  'text-outline': Type,
  'trash-outline': Trash2,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = Omit<LucideProps, 'color'> & {
  name: IconName;
  color?: string;
};

/** Drop-in replacement for `<Ionicons name={...} color={...} size={...} />`, backed by lucide-react-native. */
export function Icon({ name, ...props }: IconProps) {
  const LucideComponent = ICONS[name];
  return <LucideComponent {...props} />;
}
